#!/bin/bash

# student/example
parent=.
read dir file

if ! [ -d $dir ]
then
 mkdir $dir
fi

for i in $parent
do
 if [ $i = ??[1-3] ]
  then
   cp $i "$dir/$i"
  fi
done


otherDir=.


count=0
for i in $otherDir
do
 if [ $i = *.c ]
  then
 echo "deleting $i"
 #  rm $i
   count=$(($count+1))
  fi
done
